/** Dados fictícios de pacientes para demonstração (usado por seed-patients.ts). */
/** Data civil como DateTime (meio-dia UTC) para evitar desvio de dia no fuso. */
export function birthDateFromDdMmYyyy(s: string): Date {
  const [dd, mm, yyyy] = s.split('/');
  if (!dd || !mm || !yyyy) throw new Error(`Data de nascimento inválida: ${s}`);
  return new Date(`${yyyy}-${mm.padStart(2, '0')}-${dd.padStart(2, '0')}T12:00:00.000Z`);
}

/**
 * Mantém ano + dia civil; o **mês** passa a ser o mês atual do calendário (quando você roda o seed).
 * Dia é limitado ao último dia do mês atual (ex.: não usar 31 em fevereiro).
 */
export function birthDdMmFromDayAndYearThisMonth(dayOfMonth: number, year: number): string {
  const now = new Date();
  const mm = now.getMonth() + 1;
  const lastDay = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
  const safeDay = Math.min(Math.max(1, dayOfMonth), lastDay);
  const dd = String(safeDay).padStart(2, '0');
  const ms = String(mm).padStart(2, '0');
  return `${dd}/${ms}/${year}`;
}

export function demoAddress(p: {
  cep: string;
  endereco: string;
  numero: number;
  bairro: string;
  cidade: string;
  estado: string;
}): string {
  return `${p.endereco}, ${p.numero} — ${p.bairro}, ${p.cidade}/${p.estado} — CEP ${p.cep}`;
}

/**
 * Pacientes fictícios (dados públicos/demonstração — sem campo de login/senha).
 * Origem: importação solicitada pela equipe; CPF/email únicos como no JSON fornecido.
 */
export const demoPatientsFromImport = [
  {
    name: 'Olivia Clarice Sandra Oliveira',
    email: 'olivia.clarice.oliveira@rodrigofranco.com',
    phone: '(11) 98133-0136',
    document: '424.771.828-20',
    dataNasc: '18/01/2004',
    address: demoAddress({
      cep: '07717-470',
      endereco: 'Rua Eva',
      numero: 173,
      bairro: 'Vera Tereza',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '17.843.165-5',
      idadeDeclarada: 22,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Olivia Malu Mariane',
      pai: 'Samuel Oliver Oliveira',
      telefoneFixo: '(11) 2940-8817',
      altura: '1,73',
      peso: 71,
      tipoSanguineo: 'AB-',
      cor: 'roxo',
    },
  },
  {
    name: 'Vitória Evelyn Sophia Gomes',
    email: 'vitoriaevelyngomes@tedde.com.br',
    phone: '(11) 99428-4492',
    document: '348.766.588-38',
    dataNasc: '26/02/1977',
    address: demoAddress({
      cep: '07700-115',
      endereco: 'Avenida Presidente Kennedy',
      numero: 440,
      bairro: 'Região Central',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '42.294.107-4',
      idadeDeclarada: 49,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Simone Sebastiana',
      pai: 'Marcos Geraldo Gomes',
      telefoneFixo: '(11) 3552-8310',
      altura: '1,83',
      peso: 75,
      tipoSanguineo: 'AB+',
      cor: 'preto',
    },
  },
  {
    name: 'Fátima Silvana Costa',
    email: 'fatima-costa79@id.uff.br',
    phone: '(11) 98161-8480',
    document: '326.019.898-90',
    dataNasc: '10/05/1999',
    address: demoAddress({
      cep: '07713-035',
      endereco: 'Viela Cícero Guilhermino dos Santos',
      numero: 467,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '19.859.386-7',
      idadeDeclarada: 27,
      sexo: 'Feminino',
      signo: 'Touro',
      mae: 'Lara Ana',
      pai: 'Enrico Guilherme Costa',
      telefoneFixo: '(11) 3696-1114',
      altura: '1,56',
      peso: 76,
      tipoSanguineo: 'B-',
      cor: 'azul',
    },
  },
  {
    name: 'Priscila Manuela Liz Ferreira',
    email: 'priscila-ferreira94@hotmal.com',
    phone: '(11) 99126-2767',
    document: '563.346.298-08',
    dataNasc: '17/01/1970',
    address: demoAddress({
      cep: '07717-425',
      endereco: 'Rua Avelina',
      numero: 868,
      bairro: 'Vera Tereza',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '14.241.597-2',
      idadeDeclarada: 56,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Clarice Maya',
      pai: 'Leandro Thomas Ferreira',
      telefoneFixo: '(11) 2760-7223',
      altura: '1,60',
      peso: 57,
      tipoSanguineo: 'O-',
      cor: 'preto',
    },
  },
  {
    name: 'Carolina Adriana Novaes',
    email: 'carolina-novaes85@wizardsjc.com.br',
    phone: '(11) 98393-8108',
    document: '337.584.188-44',
    dataNasc: '26/04/1999',
    address: demoAddress({
      cep: '07716-255',
      endereco: 'Rua Antônio Teixeira',
      numero: 735,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '27.189.923-2',
      idadeDeclarada: 27,
      sexo: 'Feminino',
      signo: 'Touro',
      mae: 'Maria Manuela',
      pai: 'Martin Leandro Pedro Henrique Novaes',
      telefoneFixo: '(11) 3992-6628',
      altura: '1,83',
      peso: 81,
      tipoSanguineo: 'B-',
      cor: 'vermelho',
    },
  },
  {
    name: 'Daiane Benedita Luna Rezende',
    email: 'daiane_rezende@thibe.com.br',
    phone: '(11) 98275-4304',
    document: '561.497.338-90',
    dataNasc: '09/02/1959',
    address: demoAddress({
      cep: '07714-120',
      endereco: 'Rua Márcia Mendes',
      numero: 729,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '11.102.024-4',
      idadeDeclarada: 67,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Kamilly Bárbara Clarice',
      pai: 'Ian Kaique Juan Rezende',
      telefoneFixo: '(11) 2552-1038',
      altura: '1,62',
      peso: 67,
      tipoSanguineo: 'B+',
      cor: 'roxo',
    },
  },
  {
    name: 'Isabella Fabiana Ribeiro',
    email: 'isabella.fabiana.ribeiro@bluewash.com.br',
    phone: '(11) 98872-6937',
    document: '516.457.678-33',
    dataNasc: '19/04/1981',
    address: demoAddress({
      cep: '07713-130',
      endereco: 'Rua José Toso',
      numero: 426,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '50.598.274-2',
      idadeDeclarada: 45,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Eloá Olivia Stefany',
      pai: 'Thales Ruan Ribeiro',
      telefoneFixo: '(11) 3585-5755',
      altura: '1,83',
      peso: 65,
      tipoSanguineo: 'B+',
      cor: 'verde',
    },
  },
  {
    name: 'Isadora Isabelle Laura Almeida',
    email: 'isadora_almeida@marketingvale.com.br',
    phone: '(11) 98688-2434',
    document: '525.891.898-00',
    dataNasc: '23/03/1949',
    address: demoAddress({
      cep: '07743-040',
      endereco: 'Estrada do Ajoá',
      numero: 703,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '26.750.242-4',
      idadeDeclarada: 77,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Luciana Clara Débora',
      pai: 'Alexandre Miguel Almeida',
      telefoneFixo: '(11) 3943-3377',
      altura: '1,70',
      peso: 77,
      tipoSanguineo: 'A-',
      cor: 'verde',
    },
  },
  {
    name: 'Jéssica Allana Bárbara da Rosa',
    email: 'jessicaallanadarosa@arbitral.com',
    phone: '(11) 99992-8309',
    document: '555.515.438-03',
    dataNasc: '04/02/1965',
    address: demoAddress({
      cep: '07748-430',
      endereco: "Rua Angelo D'Assero",
      numero: 458,
      bairro: 'Vila Rosina',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '30.290.808-0',
      idadeDeclarada: 61,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Sônia Melissa Emanuelly',
      pai: 'Carlos Osvaldo da Rosa',
      telefoneFixo: '(11) 2761-3124',
      altura: '1,73',
      peso: 80,
      tipoSanguineo: 'B+',
      cor: 'laranja',
    },
  },
  {
    name: 'Agatha Laís Renata da Paz',
    email: 'agatha_dapaz@vhbadvogados.com.br',
    phone: '(11) 98403-5436',
    document: '515.071.278-71',
    dataNasc: '22/01/1946',
    address: demoAddress({
      cep: '07724-025',
      endereco: 'Rua Espírito Santo',
      numero: 419,
      bairro: 'Nova Era',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '44.964.864-3',
      idadeDeclarada: 80,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Lavínia Alessandra',
      pai: 'Carlos Eduardo Martin da Paz',
      telefoneFixo: '(11) 3811-6880',
      altura: '1,67',
      peso: 52,
      tipoSanguineo: 'A+',
      cor: 'vermelho',
    },
  },
  {
    name: 'Valentina Raquel Hadassa Brito',
    email: 'valentina.raquel.brito@gastrolight.com.br',
    phone: '(11) 98777-0941',
    document: '648.064.918-45',
    dataNasc: '15/01/1978',
    address: demoAddress({
      cep: '07715-030',
      endereco: 'Rua Imperatriz Leopoldina',
      numero: 918,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '33.600.132-0',
      idadeDeclarada: 48,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Kamilly Joana Elisa',
      pai: 'Carlos Eduardo Rodrigo Brito',
      telefoneFixo: '(11) 3778-3185',
      altura: '1,72',
      peso: 89,
      tipoSanguineo: 'O+',
      cor: 'amarelo',
    },
  },
  {
    name: 'Aparecida Luiza Andrea de Paula',
    email: 'aparecida.luiza.depaula@clubedorei.com.br',
    phone: '(11) 99670-0736',
    document: '327.704.028-38',
    dataNasc: '25/03/1968',
    address: demoAddress({
      cep: '07700-725',
      endereco: 'Rua Espanha',
      numero: 212,
      bairro: 'Região Central',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '46.798.320-3',
      idadeDeclarada: 58,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Julia Ester Rita',
      pai: 'Caleb Tiago Gabriel de Paula',
      telefoneFixo: '(11) 3550-6518',
      altura: '1,75',
      peso: 48,
      tipoSanguineo: 'AB+',
      cor: 'roxo',
    },
  },
  {
    name: 'Regina Isabelle Santos',
    email: 'regina_santos@comprehense.com.br',
    phone: '(11) 99263-1829',
    document: '711.001.778-84',
    dataNasc: '26/04/1991',
    address: demoAddress({
      cep: '07700-700',
      endereco: 'Rua Curumim',
      numero: 560,
      bairro: 'Região Central',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '21.930.752-0',
      idadeDeclarada: 35,
      sexo: 'Feminino',
      signo: 'Touro',
      mae: 'Lara Aurora Fernanda',
      pai: 'Roberto Mateus Santos',
      telefoneFixo: '(11) 3818-0818',
      altura: '1,63',
      peso: 63,
      tipoSanguineo: 'A-',
      cor: 'preto',
    },
  },
  {
    name: 'Carla Helena Valentina Peixoto',
    email: 'carla.helena.peixoto@navescorat.com.br',
    phone: '(11) 99234-7806',
    document: '771.240.928-50',
    dataNasc: '21/02/1990',
    address: demoAddress({
      cep: '07745-160',
      endereco: 'Rua Perdiz',
      numero: 544,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '35.417.071-5',
      idadeDeclarada: 36,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Sara Tereza Marina',
      pai: 'Pedro Yago Caleb Peixoto',
      telefoneFixo: '(11) 2636-3301',
      altura: '1,52',
      peso: 59,
      tipoSanguineo: 'B+',
      cor: 'vermelho',
    },
  },
  {
    name: 'Emilly Luna Sebastiana Carvalho',
    email: 'emillylunacarvalho@simoesmendonca.adv.br',
    phone: '(11) 99822-0031',
    document: '619.262.258-21',
    dataNasc: '04/02/1987',
    address: demoAddress({
      cep: '07713-285',
      endereco: 'Rua Batatais',
      numero: 889,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '29.873.828-4',
      idadeDeclarada: 39,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Stefany Márcia',
      pai: 'Osvaldo Oliver Gael Carvalho',
      telefoneFixo: '(11) 3921-4618',
      altura: '1,63',
      peso: 75,
      tipoSanguineo: 'A-',
      cor: 'laranja',
    },
  },
  {
    name: 'Gabriela Emilly Silva',
    email: 'gabriela_silva@gmx.ca',
    phone: '(11) 99588-6747',
    document: '178.345.118-15',
    dataNasc: '20/03/1996',
    address: demoAddress({
      cep: '07739-205',
      endereco: 'Rua Castro Alves',
      numero: 292,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '42.876.006-5',
      idadeDeclarada: 30,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Pietra Luciana Hadassa',
      pai: 'Fábio Elias Silva',
      telefoneFixo: '(11) 2670-3005',
      altura: '1,66',
      peso: 83,
      tipoSanguineo: 'O-',
      cor: 'verde',
    },
  },
  {
    name: 'Vitória Elza Luiza Vieira',
    email: 'vitoria_elza_vieira@estevao.ind.br',
    phone: '(11) 98182-2290',
    document: '935.601.868-54',
    dataNasc: '14/03/1961',
    address: demoAddress({
      cep: '07739-400',
      endereco: 'Rua Maria de Sales Pupo',
      numero: 687,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '31.906.490-6',
      idadeDeclarada: 65,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Nicole Fernanda',
      pai: 'Bruno Gustavo Vieira',
      telefoneFixo: '(11) 2981-6557',
      altura: '1,69',
      peso: 61,
      tipoSanguineo: 'O-',
      cor: 'amarelo',
    },
  },
  {
    name: 'Alessandra Valentina Lopes',
    email: 'alessandra_valentina_lopes@kimmay.com.br',
    phone: '(11) 98315-4867',
    document: '032.201.678-96',
    dataNasc: '03/01/1971',
    address: demoAddress({
      cep: '07726-515',
      endereco: 'Rua Bento Ferreira da Silva',
      numero: 781,
      bairro: 'Morro Grande',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '46.742.681-8',
      idadeDeclarada: 55,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Hadassa Allana Rebeca',
      pai: 'Otávio Elias Lopes',
      telefoneFixo: '(11) 2802-3894',
      altura: '1,81',
      peso: 90,
      tipoSanguineo: 'O-',
      cor: 'roxo',
    },
  },
  {
    name: 'Alícia Alícia Giovanna Nogueira',
    email: 'aliciaalicianogueira@negleribeiro.com',
    phone: '(11) 99394-9578',
    document: '178.503.708-05',
    dataNasc: '07/03/1971',
    address: demoAddress({
      cep: '07743-445',
      endereco: 'Rua Emancipador Benedito Antonio de Moraes',
      numero: 245,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '13.875.612-0',
      idadeDeclarada: 55,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Isis Analu',
      pai: 'Gustavo Cauã Ricardo Nogueira',
      telefoneFixo: '(11) 3940-0495',
      altura: '1,85',
      peso: 51,
      tipoSanguineo: 'B-',
      cor: 'amarelo',
    },
  },
  {
    name: 'Stefany Sônia Souza',
    email: 'stefany_souza@operaconstrutora.com.br',
    phone: '(11) 98312-8831',
    document: '180.922.078-52',
    dataNasc: '21/05/1972',
    address: demoAddress({
      cep: '07715-032',
      endereco: 'Rua Marechal Deodoro da Fonseca',
      numero: 492,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '18.762.509-8',
      idadeDeclarada: 54,
      sexo: 'Feminino',
      signo: 'Gêmeos',
      mae: 'Tatiane Eduarda Fabiana',
      pai: 'Giovanni Benjamin Souza',
      telefoneFixo: '(11) 3618-8803',
      altura: '1,64',
      peso: 69,
      tipoSanguineo: 'A+',
      cor: 'azul',
    },
  },
  {
    name: 'Isabelle Manuela Freitas',
    email: 'isabelle_freitas@l3ambiental.com.br',
    phone: '(11) 98447-7312',
    document: '525.237.748-01',
    dataNasc: '06/01/1965',
    address: demoAddress({
      cep: '07703-205',
      endereco: 'Rua Pedro Martins Ramos',
      numero: 663,
      bairro: 'Nova Caieiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '33.392.850-7',
      idadeDeclarada: 61,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Maria Isabel Kamilly',
      pai: 'Yuri Kevin Freitas',
      telefoneFixo: '(11) 3755-3114',
      altura: '1,67',
      peso: 57,
      tipoSanguineo: 'A-',
      cor: 'roxo',
    },
  },
  {
    name: 'Sônia Mirella da Paz',
    email: 'sonia_dapaz@inepar.com.br',
    phone: '(11) 99934-3971',
    document: '357.409.278-46',
    dataNasc: '26/01/1958',
    address: demoAddress({
      cep: '07747-285',
      endereco: 'Rua Maria Gaspar Teixeira',
      numero: 492,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '10.701.057-4',
      idadeDeclarada: 68,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Marlene Helena Teresinha',
      pai: 'Benjamin Henry Murilo da Paz',
      telefoneFixo: '(11) 3830-1337',
      altura: '1,62',
      peso: 46,
      tipoSanguineo: 'B+',
      cor: 'azul',
    },
  },
  {
    name: 'Bruna Olivia Emilly Almada',
    email: 'bruna_almada@bluespropaganda.com',
    phone: '(11) 99978-7583',
    document: '282.324.348-80',
    dataNasc: '22/03/1965',
    address: demoAddress({
      cep: '07726-545',
      endereco: 'Rua Antônio Decresci',
      numero: 987,
      bairro: 'Morro Grande',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '50.257.425-2',
      idadeDeclarada: 61,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Rafaela Luzia',
      pai: 'Daniel Henrique Gabriel Almada',
      telefoneFixo: '(11) 3856-9500',
      altura: '1,80',
      peso: 58,
      tipoSanguineo: 'O-',
      cor: 'vermelho',
    },
  },
  {
    name: 'Maya Sabrina Nunes',
    email: 'maya-nunes90@microlasersp.com.br',
    phone: '(11) 98216-2615',
    document: '768.867.758-04',
    dataNasc: '08/04/1958',
    address: demoAddress({
      cep: '07700-155',
      endereco: 'Rua Eugênio Bertti',
      numero: 787,
      bairro: 'Região Central',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '27.914.772-7',
      idadeDeclarada: 68,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Josefa Caroline',
      pai: 'Miguel Renato Nunes',
      telefoneFixo: '(11) 3767-9181',
      altura: '1,61',
      peso: 68,
      tipoSanguineo: 'AB-',
      cor: 'amarelo',
    },
  },
  {
    name: 'Manuela Luciana Rocha',
    email: 'manuela_luciana_rocha@konzeption.com.br',
    phone: '(11) 98475-7528',
    document: '034.646.728-40',
    dataNasc: '14/05/2005',
    address: demoAddress({
      cep: '07743-050',
      endereco: 'Rua Lindolfo Soares de Campos',
      numero: 443,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '50.121.564-5',
      idadeDeclarada: 21,
      sexo: 'Feminino',
      signo: 'Touro',
      mae: 'Bruna Marina Laís',
      pai: 'Oliver Joaquim Rocha',
      telefoneFixo: '(11) 2977-7983',
      altura: '1,61',
      peso: 55,
      tipoSanguineo: 'B-',
      cor: 'laranja',
    },
  },
  {
    name: 'Eduarda Ana Giovana Alves',
    email: 'eduarda_ana_alves@metroquali.com.br',
    phone: '(11) 99522-0309',
    document: '792.822.928-51',
    dataNasc: '06/02/1973',
    address: demoAddress({
      cep: '07743-330',
      endereco: 'Rua Vereador Hugo Pereira da Silva',
      numero: 617,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '29.044.790-2',
      idadeDeclarada: 53,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Rebeca Aline',
      pai: 'Nicolas Augusto Nicolas Alves',
      telefoneFixo: '(11) 2541-8276',
      altura: '1,78',
      peso: 68,
      tipoSanguineo: 'A-',
      cor: 'preto',
    },
  },
  {
    name: 'Luiza Camila Aparício',
    email: 'luizacamilaaparicio@sebrace.com.br',
    phone: '(11) 98549-0449',
    document: '165.949.748-58',
    dataNasc: '05/03/1953',
    address: demoAddress({
      cep: '07716-265',
      endereco: 'Rua dos Pinheirais',
      numero: 709,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '43.419.732-4',
      idadeDeclarada: 73,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Carla Ester',
      pai: 'Mário Levi Aparício',
      telefoneFixo: '(11) 3565-6802',
      altura: '1,67',
      peso: 57,
      tipoSanguineo: 'B-',
      cor: 'vermelho',
    },
  },
  {
    name: 'Maya Milena Eloá Pires',
    email: 'maya_milena_pires@centerdiesel.com.br',
    phone: '(11) 98701-8409',
    document: '435.543.238-61',
    dataNasc: '08/03/1968',
    address: demoAddress({
      cep: '07749-225',
      endereco: 'Rua João Rosolém',
      numero: 117,
      bairro: 'Vila Rosina',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '15.998.913-9',
      idadeDeclarada: 58,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Juliana Alícia Olivia',
      pai: 'Joaquim Rodrigo Pires',
      telefoneFixo: '(11) 3541-1438',
      altura: '1,85',
      peso: 61,
      tipoSanguineo: 'O+',
      cor: 'verde',
    },
  },
  {
    name: 'Gabriela Bianca Adriana da Mata',
    email: 'gabriela-damata75@gmx.de',
    phone: '(11) 99786-1185',
    document: '894.363.878-73',
    dataNasc: '01/01/1958',
    address: demoAddress({
      cep: '07741-000',
      endereco: 'Rua Boracéia',
      numero: 756,
      bairro: 'Laranjeiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '26.641.261-0',
      idadeDeclarada: 68,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Maitê Marli Letícia',
      pai: 'Francisco Manoel da Mata',
      telefoneFixo: '(11) 3924-7906',
      altura: '1,63',
      peso: 62,
      tipoSanguineo: 'B-',
      cor: 'laranja',
    },
  },
  {
    name: 'Lúcia Luciana Aparecida Assis',
    email: 'lucia.luciana.assis@detorsul.com',
    phone: '(11) 98514-1096',
    document: '292.246.868-26',
    dataNasc: '04/03/1957',
    address: demoAddress({
      cep: '07704-140',
      endereco: 'Rua Constantino Toigo',
      numero: 716,
      bairro: 'Nova Caieiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '18.337.687-0',
      idadeDeclarada: 69,
      sexo: 'Feminino',
      signo: 'Peixes',
      mae: 'Silvana Fernanda',
      pai: 'Benjamin Diogo Geraldo Assis',
      telefoneFixo: '(11) 3626-2269',
      altura: '1,53',
      peso: 55,
      tipoSanguineo: 'O+',
      cor: 'preto',
    },
  },
] as const;

/**
 * Mesmo conjunto que `demoPatientsFromImport`; aqui omitimos `dataNasc` fixa e usamos dia+ano na data
 * **`birthDdMmFromDayAndYearThisMonth`**: mês da data gravada = mês atual ao rodar o seed (dashboard).
 */
export const demoPatientsBirthdayCurrentMonthImport = [
  {
    name: 'Fernanda Maya Moraes',
    email: 'fernandamayamoraes@azulcargo.com.br',
    phone: '(11) 99839-6914',
    document: '293.978.018-80',
    birthDayOfMonth: 3,
    birthYear: 1980,
    dataNascOriginal: '03/01/1980',
    address: demoAddress({
      cep: '07713-120',
      endereco: 'Rua Rosalina Toso Antônio',
      numero: 769,
      bairro: 'Serpa',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '47.760.147-9',
      idadeDeclarada: 46,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Ana Elisa',
      pai: 'Danilo Vitor Caleb Moraes',
      telefoneFixo: '(11) 2567-2004',
      altura: '1,77',
      peso: 63,
      tipoSanguineo: 'AB+',
      cor: 'vermelho',
    },
  },
  {
    name: 'Isabella Francisca Mendes',
    email: 'isabella_mendes@suzano.com.br',
    phone: '(11) 98175-4519',
    document: '887.261.208-01',
    birthDayOfMonth: 27,
    birthYear: 1954,
    dataNascOriginal: '27/01/1954',
    address: demoAddress({
      cep: '07717-453',
      endereco: 'Rua Estevão Gondari',
      numero: 973,
      bairro: 'Vera Tereza',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '28.164.103-1',
      idadeDeclarada: 72,
      sexo: 'Feminino',
      signo: 'Aquário',
      mae: 'Emily Vanessa',
      pai: 'Igor Vinicius Nelson Mendes',
      telefoneFixo: '(11) 3812-2928',
      altura: '1,51',
      peso: 85,
      tipoSanguineo: 'A-',
      cor: 'verde',
    },
  },
  {
    name: 'Clarice Bruna Aragão',
    email: 'claricebrunaaragao@panevale.com.br',
    phone: '(11) 99757-8089',
    document: '000.517.948-37',
    birthDayOfMonth: 6,
    birthYear: 1970,
    dataNascOriginal: '06/05/1970',
    address: demoAddress({
      cep: '07700-005',
      endereco: 'Rua João Dártora',
      numero: 470,
      bairro: 'Região Central',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '18.740.509-8',
      idadeDeclarada: 56,
      sexo: 'Feminino',
      signo: 'Touro',
      mae: 'Aurora Louise Helena',
      pai: 'Pietro Sebastião Luiz Aragão',
      telefoneFixo: '(11) 3588-3207',
      altura: '1,57',
      peso: 54,
      tipoSanguineo: 'B-',
      cor: 'laranja',
    },
  },
  {
    name: 'Luna Fernanda Gabrielly Rocha',
    email: 'lunafernandarocha@viamoc.com.br',
    phone: '(11) 98655-6832',
    document: '654.597.338-04',
    birthDayOfMonth: 20,
    birthYear: 2003,
    dataNascOriginal: '20/04/2003',
    address: demoAddress({
      cep: '07734-020',
      endereco: 'Rua Uchôa',
      numero: 979,
      bairro: 'Santa Inês',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '10.793.850-9',
      idadeDeclarada: 23,
      sexo: 'Feminino',
      signo: 'Áries',
      mae: 'Allana Laura Benedita',
      pai: 'Osvaldo Mateus Miguel Rocha',
      telefoneFixo: '(11) 3739-7108',
      altura: '1,82',
      peso: 80,
      tipoSanguineo: 'O-',
      cor: 'verde',
    },
  },
  {
    name: 'Louise Liz Bernardes',
    email: 'louiselizbernardes@transporteveloz.com.br',
    phone: '(11) 99570-7454',
    document: '456.225.868-36',
    birthDayOfMonth: 9,
    birthYear: 1971,
    dataNascOriginal: '09/01/1971',
    address: demoAddress({
      cep: '07703-055',
      endereco: 'Rua Fortunato Pollon',
      numero: 779,
      bairro: 'Nova Caieiras',
      cidade: 'Caieiras',
      estado: 'SP',
    }),
    anamnesis: {
      rg: '39.970.261-1',
      idadeDeclarada: 55,
      sexo: 'Feminino',
      signo: 'Capricórnio',
      mae: 'Vera Luiza',
      pai: 'Diogo Marcos Vinicius Bernardo Bernardes',
      telefoneFixo: '(11) 2984-5314',
      altura: '1,61',
      peso: 52,
      tipoSanguineo: 'AB-',
      cor: 'roxo',
    },
  },
] as const;
